
@endpoint = http://localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjQ3MzMyODI0LCJleHAiOjE2NDczNDAwMjR9.nSh2SiQ5SJ9Uwui5ZrDJUkZvntCl5TH-vqjHUfisJ5M
### Login
POST {{ endpoint }}/login
content-type: application/json

{
  "regNumber": "U000001",
  "password": "ADMIN"
}

### Liste des employés
GET {{ endpoint }}/employee
x-access-token : {{token}}

### Ajout d'un employé
POST {{ endpoint }}/employee
x-access-token : {{token}}
content-type: application/json

{
  "regNumber": "U000101",
  "password": "U000101",
  "role": "user"
}

### Affiche un employé selon son ID
GET {{ endpoint }}/employee/28
x-access-token : {{token}}

### Supprime un employé selon son ID
DELETE {{ endpoint }}/employee/30
x-access-token : {{token}}

### Modifier les données d'un employé selon son ID
PATCH {{ endpoint }}/employee/28
x-access-token : {{token}}
content-type: application/json

{
"password": "U002388"
}


### Ajoute un statut sur un employé pour un jour donné
POST {{ endpoint }}/affectedStatus/employee/5/date/2022-07-30
x-access-token : {{token}}
content-type: application/json

{
  "statusId": 4
}

### Modifie un statut sur un employé pour un jour donné
PATCH {{ endpoint }}/affectedStatus/employee/5/date/2022-07-26
x-access-token : {{token}}
content-type: application/json

{
  "statusId": 4,
  "comment": "ça marche"
}

### Supprime un statut sur un employé pour un jour donné
DELETE {{ endpoint }}/affectedStatus/employee/5/date/2022-07-26
x-access-token : {{token}}


### Liste des status
GET {{ endpoint }}/status
x-access-token : {{token}}

### Un statut par son ID
GET {{ endpoint }}/status/50
x-access-token : {{token}}

### Affichage du planning
GET {{ endpoint }}/planning
x-access-token : {{token}}
### Affichage des teams
GET {{ endpoint }}/team
x-access-token : {{token}}

### Ajout d'un nouveau shift
POST {{ endpoint }}/shift
x-access-token : {{token}}
content-type: application/json

{
  "date": "2023-03-15",
  "teams": [
    {"team_id": 1, "shift": "AM"},
    {"team_id": 2, "shift": ""},
    {"team_id": 3, "shift": "M"},
    {"team_id": 4, "shift": ""},
    {"team_id": 5, "shift": "N"}
  ]
}

### Modification des shifts
PATCH {{ endpoint }}/shift
x-access-token : {{token}}
content-type: application/json

{
  "date": "2023-03-15",
  "teams": [
    {"team_id": 1, "shift": "N"},
    {"team_id": 2, "shift": "N"},
    {"team_id": 3, "shift": "N"},
    {"team_id": 4, "shift": "N"},
    {"team_id": 5, "shift": "N"}
  ]
}
