
@endpoint = http://localhost:3000

### Login
POST {{ endpoint }}/login
content-type: application/json

{
  "regNumber": "U000002",
  "password": "USER"
}

### Liste des employés
GET {{ endpoint }}/employee
x-access-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsImlhdCI6MTY0NjIzMzUyNSwiZXhwIjoxNjQ2MjQwNzI1fQ.Xnr88cArJRu4mkZVuxYjf5xv8VQovLX7ZU25dL39MVk

### Ajoute un statut sur un employé pour un jour donné
POST {{ endpoint }}/employee/11/date/2022-06-26
content-type: application/json

{
  "statusId": 1,
  "teamId": null,
  "comment": ""
}
