-- Deploy organizer:init to pg

BEGIN;

CREATE TABLE "team" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "noun" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "employee" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "reg_number" TEXT NOT NULL,
    "name" TEXT,
    "lastname" TEXT,
    "role" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "function" TEXT,
    "profile_picture" TEXT,
    "team_id" int REFERENCES "team"("id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "status" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "label" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "affected_status" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "comment" TEXT,
    "date" DATE NOT NULL,
    "team_id" int REFERENCES "team"("id"),
    "employee_id" int NOT NULL REFERENCES "employee"("id"),
    "status_id" int NOT NULL REFERENCES "status"("id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "shift" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "label" TEXT,
    "date" DATE NOT NULL,
    "team_id" int NOT NULL REFERENCES "team"("id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ
);

--
-- Postgres avec le fait d'ajouter IDENTITY BY DEFAULT au lieu de ALWAYS ne met pas à jour le curseur de l'incrément de la séquence de façon implicite !
-- Il faut donc mettre à jour la valeur courante de chacune des séquences en séléctionnant l'id maximum de chaque table
--

SELECT setval('team_id_seq', (SELECT MAX(id) from "team"));
SELECT setval('employee_id_seq', (SELECT MAX(id) from "employee"));
SELECT setval('status_id_seq', (SELECT MAX(id) from "status"));
SELECT setval('status_id_seq', (SELECT MAX(id) from "affected_status"));
SELECT setval('shift_id_seq', (SELECT MAX(id) from "shift"));

COMMIT;
